import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '../components/theme-provider'
import Header from '@/components/header'
import Footer from '@/components/footer'
import { cn } from '@/lib/utils'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
})

const jetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          /* turn into flex column so the footer goes all the way down */
          'flex min-h-screen flex-col font-sans antialiased',
          `${inter.variable} ${jetbrainsMono.variable}`
        )}
      >
        <ThemeProvider>
          {' '}
          {/* wrapping into client compoenent doesn't turn the entire app into client component */}
          <Header />
          <main className='grow'>{children}</main>{' '}
          {/* like putting margin top auto on footer, to make space; children is the content of the page */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
