import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn( /* turn into flex column so the footer goes all the way down */
          'flex min-h-screen flex-col font-sans antialiased',
          `${geistSans.variable} ${geistMono.variable}`
        )}
      >
        <ThemeProvider> {/* wrapping into client compoenent doesn't turn the entire app into client component */}
          <Header />
          <main className="grow">{children}</main> {/* like putting margin top auto on footer, to make space; children is the content of the page */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
